### ISSUE TITLE
Show proper error when no fortune is found

### ISSUE THREAD

**Issue by vromero** [gofortune/gofortune#14]
Currently is showing a horrendous: 

```
panic: No branch was randomly selected

goroutine 6 [running]:
github.com/gofortune/gofortune/lib/fortune.GetRandomLeafNode(0x42c80000ffc00000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/victor/src/gofortune/gofortune/src/github.com/gofortune/gofortune/lib/fortune/probabilities.go:18 +0x107
github.com/gofortune/gofortune/lib/fortune.GetRandomFortune.func1(0x42c80000ffc00000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/victor/src/gofortune/gofortune/src/github.com/gofortune/gofortune/lib/fortune/fortune.go:32 +0x55
created by github.com/gofortune/gofortune/lib/fortune.GetRandomFortune
        /home/victor/src/gofortune/gofortune/src/github.com/gofortune/gofortune/lib/fortune/fortune.go:60 +0x95
```

**Comment by vromero** [comment]
Closing as no longer valid.

The original panic (`panic: No branch was randomly selected`) has been addressed in commit f19f6c6 ("refactor: improve error handling and remove panics").

`GetRandomLeafNode` in `pkg/fortune/probabilities.go:9-24` now returns an `error` instead of panicking, and the error is propagated up through `GetRandomFortune` / `GetLengthFilteredRandomFortune` and printed to the user by `printFortune` in `cmd/fortune.go:148-152`.

If the exact wording of the message still needs polish, that can be tracked in a separate, more focused issue.
